class MenuItemDetail {
  final int id;
  final int restaurantId;
  final String name;
  final String category;
  final String description;
  final double price;

  MenuItemDetail(
      {this.category,
      this.id,
      this.restaurantId,
      this.name,
      this.description,
      this.price});

  @override
  // TODO: implement props
  List<Object> get props =>
      [id, category, restaurantId, name, description, price];

  static List<MenuItemDetail> menuItems = [
    MenuItemDetail(
      id: 1,
      restaurantId: 1,
      name: 'Margherita',
      category: 'Pizza',
      description: 'Tomat, ost',
      price: 85.00,
    ),
    MenuItemDetail(
      id: 2,
      restaurantId: 1,
      name: 'Prosciutto',
      category: 'Pizza',
      description: 'Tomat, ost, skinke',
      price: 90.00,
    ),
    MenuItemDetail(
      id: 3,
      restaurantId: 1,
      name: 'Veni, Vedi, Vici',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, champignon',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 4,
      restaurantId: 1,
      name: 'American Classic',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni',
      price: 90.00,
    ),
    MenuItemDetail(
      id: 5,
      restaurantId: 1,
      name: 'Pancetta',
      category: 'Pizza',
      description: 'Tomat, ost, bacon, skinke, pepperoni',
      price: 96.00,
    ),
    MenuItemDetail(
      id: 6,
      restaurantId: 1,
      name: 'Bolognese',
      category: 'Pizza',
      description: 'Tomat, ost, kødsovs, løg',
      price: 90.00,
    ),
    MenuItemDetail(
      id: 7,
      restaurantId: 1,
      name: 'Hawaii',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, ananas',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 8,
      restaurantId: 1,
      name: 'Montanara',
      category: 'Pizza',
      description: 'Tomat, ost, peperoni, oliven, peberfrugt',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 9,
      restaurantId: 1,
      name: 'Calzone',
      category: 'Pizza',
      description: 'Tomat, ost, skinke',
      price: 93.00,
    ),
    MenuItemDetail(
      id: 10,
      restaurantId: 1,
      name: 'Gorgonzola',
      category: 'Pizza',
      description: 'Tomat, ost, marineret kødstrimler, spinat, gorgonzola, løg',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 11,
      restaurantId: 1,
      name: 'Bismarck',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, æg',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 12,
      restaurantId: 1,
      name: 'Pollo',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, pesto, peberfrugt, løg, hvidløg',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 13,
      restaurantId: 1,
      name: 'Funghi',
      category: 'Pizza',
      description: 'Tomat, ost, marineret kødstrimler, champignon, mozarella',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 14,
      restaurantId: 1,
      name: 'Ami',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, bernaise',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 15,
      restaurantId: 1,
      name: 'Molto Bene',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, kylling, løg, pesto',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 16,
      restaurantId: 1,
      name: 'Kebab Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, salat, agurk, dressing',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 17,
      restaurantId: 1,
      name: 'Kyllinge Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, kylling,  salat, agurk, dressing',
      price: 98.00,
    ),
    MenuItemDetail(
      id: 18,
      restaurantId: 1,
      name: 'Okse Pizza',
      category: 'Pizza',
      description:
          'Tomat, ost, kødstrimler, champignon, gorgonzola, løg, jalapenos',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 19,
      restaurantId: 1,
      name: 'Durum',
      category: 'Kebab',
      description: 'Tomat, ost, kebab, salat, agurk, rødløg, dressing',
      price: 52.00,
    ),
    MenuItemDetail(
      id: 20,
      restaurantId: 1,
      name: 'Kyllinge Durum',
      category: 'Kebab',
      description: 'Tomat, ost, kylling, salat, agurk, rødløg, dressing',
      price: 52.00,
    ),
    MenuItemDetail(
      id: 21,
      restaurantId: 1,
      name: 'Falafel Durum',
      category: 'Kebab',
      description: 'Tomat, ost, falafel, salat, agurk, rødløg, dressing',
      price: 52.00,
    ),
    MenuItemDetail(
      id: 22,
      restaurantId: 1,
      name: 'Pita',
      category: 'Kebab',
      description: 'Tomat, ost, kebab, salat, agurk, rødløg, dressing',
      price: 40.00,
    ),
    MenuItemDetail(
      id: 23,
      restaurantId: 1,
      name: 'Kyllinge Pita',
      category: 'Kebab',
      description: 'Tomat, ost, kylling, salat, agurk, rødløg, dressing',
      price: 40.00,
    ),
    MenuItemDetail(
      id: 24,
      restaurantId: 1,
      name: 'Falafel Pita',
      category: 'Kebab',
      description: 'Tomat, ost, falafel, salat, agurk, rødløg, dressing',
      price: 40.00,
    ),
    MenuItemDetail(
      id: 25,
      restaurantId: 1,
      name: 'Torino',
      category: 'Vegetar',
      description:
          'Tomat, ost, peberfrugt, mozeralla, cherrytomat, pesto, basilikum',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 26,
      restaurantId: 1,
      name: 'Primavera',
      category: 'Vegetar',
      description: 'Tomat, ost, champignon, løg, oliven, majs',
      price: 95.00,
    ),
    MenuItemDetail(
      id: 27,
      restaurantId: 1,
      name: 'Sodavand 0,33 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 15.00,
    ),
    MenuItemDetail(
      id: 27,
      restaurantId: 1,
      name: 'Sodavand 0,5 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 22.00,
    ),
    MenuItemDetail(
      id: 28,
      restaurantId: 1,
      name: 'Sodavand 1,5 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 35.00,
    ),
    MenuItemDetail(
      id: 1,
      restaurantId: 2,
      name: 'Pizza 1',
      category: 'Pizza',
      description: 'Tomat, ost',
      price: 61.00,
    ),
    MenuItemDetail(
      id: 2,
      restaurantId: 2,
      name: 'Pizza 2',
      category: 'Pizza',
      description: 'Tomat, ost, skinke',
      price: 66.00,
    ),
    MenuItemDetail(
      id: 3,
      restaurantId: 2,
      name: 'Pizza 3',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni',
      price: 66.00,
    ),
    MenuItemDetail(
      id: 4,
      restaurantId: 2,
      name: 'Pizza 4',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, ananas',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 5,
      restaurantId: 2,
      name: 'Pizza 5',
      category: 'Pizza',
      description: 'Tomat, ost, kødsovs, løg',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 6,
      restaurantId: 2,
      name: 'Pizza 6',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, champignon',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 7,
      restaurantId: 2,
      name: 'Pizza 7',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, cocktailpølser',
      price: 74.00,
    ),
    MenuItemDetail(
      id: 8,
      restaurantId: 2,
      name: 'Pizza 10',
      category: 'Pizza',
      description: 'Tomat, ost, kødstrimler, champignon, løg',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 9,
      restaurantId: 2,
      name: 'Pizza 12',
      category: 'Pizza',
      description: 'Tomat, ost, kødstrimler, skinke, gorgonzola',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 10,
      restaurantId: 2,
      name: 'Pizza 13',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, ananas, jalapenos',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 11,
      restaurantId: 2,
      name: 'Pizza 14',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, cocktailpølser, pepperoni',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 12,
      restaurantId: 2,
      name: 'Pizza 15',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, jalapenos, gorgonzola',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 12,
      restaurantId: 2,
      name: 'Pizza 16',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, pepperoni, bacon',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 13,
      restaurantId: 2,
      name: 'Pizza 17',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, bacon, løg, æg',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 14,
      restaurantId: 2,
      name: 'Pizza 18',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, kødstrimler, jalapenos',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 15,
      restaurantId: 2,
      name: 'Pizza 19',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, hakket oksekød, paprika, hvidløg',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 16,
      restaurantId: 2,
      name: 'Pizza 20',
      category: 'Pizza',
      description: 'Tomat, ost, kødstrimler, champignon, gorgonzola, hvidløg',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 17,
      restaurantId: 2,
      name: 'Pizza 21',
      category: 'Pizza',
      description: 'Tomat, ost, hakket oksekød, pepperoni, champignon',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 18,
      restaurantId: 2,
      name: 'Pizza 22',
      category: 'Pizza',
      description:
          'Tomat, ost, hakket oksekød, pepperoni, bacon, chili, hvidløg',
      price: 83.00,
    ),
    MenuItemDetail(
      id: 19,
      restaurantId: 2,
      name: 'Pizza 23',
      category: 'Pizza',
      description:
          'Tomat, ost, hakket oksekød, pepperoni, jalapenos, gorgonzola',
      price: 83.00,
    ),
    MenuItemDetail(
      id: 20,
      restaurantId: 2,
      name: 'Pizza 24',
      category: 'Pizza',
      description: 'Tomat, ost, hakket oksekød, kødstrimler, bacon, gorgonzola',
      price: 83.00,
    ),
    MenuItemDetail(
      id: 21,
      restaurantId: 2,
      name: 'Pizza 25',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, bacon, cocktailpølser, champignon',
      price: 83.00,
    ),
    MenuItemDetail(
      id: 22,
      restaurantId: 2,
      name: 'Pizza 53',
      category: 'Pizza',
      description: 'Tomat, ost, marineret oksefillet, løg, champignon, paprika',
      price: 87.00,
    ),
    MenuItemDetail(
      id: 22,
      restaurantId: 2,
      name: 'Pizza 54',
      category: 'Pizza',
      description:
          'Tomat, ost, marineret svinemørbrad, løg, champignon, gorgonzola',
      price: 87.00,
    ),
    MenuItemDetail(
      id: 23,
      restaurantId: 2,
      name: 'Pizza 144',
      category: 'Pizza',
      description:
          'Tomat, ost, kylling, kartoffel, bacon, friske tomater, rosmarin',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 24,
      restaurantId: 2,
      name: 'Pizza 145',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, kartoffel, hakket oksekød, pesto',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 25,
      restaurantId: 2,
      name: 'Pizza 146',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, skinke',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 26,
      restaurantId: 2,
      name: 'Pizza 147',
      category: 'Pizza',
      description: 'Tomat, ost, shawarma, kylling, paprika og løg',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 27,
      restaurantId: 2,
      name: 'Pizza 148',
      category: 'Pizza',
      description: 'Tomat, ost, shawarma, kylling, paprika, chili og hvidløg',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 27,
      restaurantId: 2,
      name: 'Pizza 148',
      category: 'Pizza',
      description: 'Tomat, ost, shawarma, champignon, løg, chili, bernaise',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 28,
      restaurantId: 2,
      name: 'Pizza 26',
      category: 'Vegetar',
      description: 'Tomat, ost, champignon, artiskok, paprika, gorgonzola',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 29,
      restaurantId: 2,
      name: 'Pizza 43',
      category: 'Vegetar',
      description: 'Tomat, ost, kartoffel, rosmarin, pesto',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 30,
      restaurantId: 2,
      name: 'Pizza 44',
      category: 'Vegetar',
      description: 'Tomat, ost, semidried tomat, stegt aubergine og spinat',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 31,
      restaurantId: 2,
      name: 'Pizza 45',
      category: 'Vegetar',
      description: 'Tomat, ost, stegt squash, rucola, semidried tomat',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 32,
      restaurantId: 2,
      name: 'Pizza 46',
      category: 'Vegetar',
      description: 'Tomat, ost, champignon, artiskok, løg, oliven og paprika',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 33,
      restaurantId: 2,
      name: 'Shawarma Durum',
      category: 'Kebab',
      description: 'salat, dressing, tomat, shawarma',
      price: 63.00,
    ),
    MenuItemDetail(
      id: 34,
      restaurantId: 2,
      name: 'Kylling Durum',
      category: 'Kebab',
      description: 'salat, dressing, tomat, kylling',
      price: 63.00,
    ),
    MenuItemDetail(
      id: 35,
      restaurantId: 2,
      name: 'Falafel Durum',
      category: 'Kebab',
      description: 'salat, dressing, tomat, falafel',
      price: 63.00,
    ),
    MenuItemDetail(
      id: 36,
      restaurantId: 2,
      name: 'Sodavand 0,33 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 18.00,
    ),
    MenuItemDetail(
      id: 37,
      restaurantId: 2,
      name: 'Sodavand 1,5 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 42.00,
    ),
    MenuItemDetail(
      id: 38,
      restaurantId: 2,
      name: 'Tubord Øl 0,33 L',
      category: 'Drinks',
      description: 'Tuborg',
      price: 20.00,
    ),
    MenuItemDetail(
      id: 1,
      restaurantId: 3,
      name: 'Margarita',
      category: 'Pizza',
      description: 'Tomat, ost',
      price: 61.00,
    ),
    MenuItemDetail(
      id: 2,
      restaurantId: 3,
      name: 'Vesuvio',
      category: 'Pizza',
      description: 'Tomat, ost, skinke',
      price: 66.00,
    ),
    MenuItemDetail(
      id: 3,
      restaurantId: 3,
      name: 'Capriccisoa',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, champignon',
      price: 68.00,
    ),
    MenuItemDetail(
      id: 4,
      restaurantId: 3,
      name: 'Napoli',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, bacon',
      price: 71.00,
    ),
    MenuItemDetail(
      id: 5,
      restaurantId: 3,
      name: 'Hawaii',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, ananas',
      price: 68.00,
    ),
    MenuItemDetail(
      id: 6,
      restaurantId: 3,
      name: 'Thomas Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, pepperoni',
      price: 71.00,
    ),
    MenuItemDetail(
      id: 7,
      restaurantId: 3,
      name: 'Bacon',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, bacon, løg',
      price: 71.00,
    ),
    MenuItemDetail(
      id: 8,
      restaurantId: 3,
      name: 'Bolognese',
      category: 'Pizza',
      description: 'Tomat, ost, kødsovs, løg',
      price: 68.00,
    ),
    MenuItemDetail(
      id: 9,
      restaurantId: 3,
      name: 'Romana',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, cocktailpølser, bacon, pepperoni',
      price: 78.00,
    ),
    MenuItemDetail(
      id: 10,
      restaurantId: 3,
      name: 'Sea Food',
      category: 'Pizza',
      description: 'Tomat, ost, rejer, muslinger, tunfisk, hvidløg',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 11,
      restaurantId: 3,
      name: 'Dala Casa',
      category: 'Pizza',
      description: 'Tomat, ost, kødstrimler, champignon, løg, paprika',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 12,
      restaurantId: 3,
      name: 'Mama Mia',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, pepperoni, bacon',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 13,
      restaurantId: 3,
      name: 'DTU special',
      category: 'Pizza',
      description: 'Tomat, ost, oksekødstrimler, kødboller, bacon',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 14,
      restaurantId: 3,
      name: 'Matador',
      category: 'Pizza',
      description: 'Tomat, ost, oksestrimler, løg, champignon, bernaise',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 15,
      restaurantId: 3,
      name: 'La Fellini',
      category: 'Pizza',
      description: 'Tomat, ost, gorgonzola, champignon, pepperoni',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 16,
      restaurantId: 3,
      name: 'Oriental',
      category: 'Pizza',
      description: 'Tomat, ost, shawarma, champignon, løg, jalapenos',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 17,
      restaurantId: 3,
      name: 'American',
      category: 'Pizza',
      description: 'Tomat, ost, hakket oksekød, pepperoni, bacon, chili',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 18,
      restaurantId: 3,
      name: 'La Sosta',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, salat, dressing',
      price: 73.00,
    ),
    MenuItemDetail(
      id: 18,
      restaurantId: 3,
      name: 'Lyngby',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, salat, dressing',
      price: 73.00,
    ),
    MenuItemDetail(
      id: 19,
      restaurantId: 3,
      name: 'Kebab Pita',
      category: 'Kebab',
      description: 'Kebab, salat, dressing, agurk',
      price: 44.00,
    ),
    MenuItemDetail(
      id: 20,
      restaurantId: 3,
      name: 'Kylling Pita',
      category: 'Kebab',
      description: 'Kylling, salat, dressing, agurk',
      price: 45.00,
    ),
    MenuItemDetail(
      id: 21,
      restaurantId: 3,
      name: 'Kebab Durumrulle',
      category: 'Kebab',
      description: 'Kebab, salat, dressing, agurk',
      price: 60.00,
    ),
    MenuItemDetail(
      id: 22,
      restaurantId: 3,
      name: 'Kebab Pita',
      category: 'Kebab',
      description: 'Kylling, salat, dressing, agurk',
      price: 61.00,
    ),
    MenuItemDetail(
      id: 23,
      restaurantId: 3,
      name: 'Sodavand 0,33 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 13.00,
    ),
    MenuItemDetail(
      id: 24,
      restaurantId: 3,
      name: 'Sodavand 0,5 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 22.00,
    ),
    MenuItemDetail(
      id: 25,
      restaurantId: 3,
      name: 'Cocio 0,4 L',
      category: 'Drinks',
      description: 'Cocio',
      price: 22.00,
    ),
    MenuItemDetail(
      id: 26,
      restaurantId: 3,
      name: 'Vegetarania',
      category: 'Vegetar',
      description:
          'Tomat, ost, champignon, løg, paprika, ananas, asparges, spinat',
      price: 72.00,
    ),
    MenuItemDetail(
      id: 1,
      restaurantId: 4,
      name: 'Margarita',
      category: 'Pizza',
      description: 'Tomat, ost',
      price: 59.00,
    ),
    MenuItemDetail(
      id: 2,
      restaurantId: 4,
      name: 'Capricciosa',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, champignon',
      price: 73.00,
    ),
    MenuItemDetail(
      id: 3,
      restaurantId: 4,
      name: 'Hawaii',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, ananas',
      price: 73.00,
    ),
    MenuItemDetail(
      id: 4,
      restaurantId: 4,
      name: 'Torino',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, pepperoni',
      price: 75.00,
    ),
    MenuItemDetail(
      id: 5,
      restaurantId: 4,
      name: 'Mizaro',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, paprika',
      price: 73.00,
    ),
    MenuItemDetail(
      id: 6,
      restaurantId: 4,
      name: 'Napoli',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, kebab, bernaise',
      price: 78.00,
    ),
    MenuItemDetail(
      id: 7,
      restaurantId: 4,
      name: 'Gorgonzola',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, pepperoni, cocktailpølser, gorgonzola',
      price: 84.00,
    ),
    MenuItemDetail(
      id: 8,
      restaurantId: 4,
      name: 'Italien',
      category: 'Pizza',
      description: 'Tomat, ost, kødsovs, løg',
      price: 73.00,
    ),
    MenuItemDetail(
      id: 9,
      restaurantId: 4,
      name: 'Dalia',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, pepperoni, bacon, hakket oksekød',
      price: 87.00,
    ),
    MenuItemDetail(
      id: 10,
      restaurantId: 4,
      name: 'Nicol',
      category: 'Pizza',
      description: 'Tomat, ost, bacon, kylling, kebab',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 11,
      restaurantId: 4,
      name: 'Gigi',
      category: 'Pizza',
      description: 'Tomat, ost, kødstrimler, champignon, løg, pesto',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 12,
      restaurantId: 4,
      name: 'Nanosa',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, paprika, ananas',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 13,
      restaurantId: 4,
      name: 'Moma',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, friske tomater, pesto',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 14,
      restaurantId: 4,
      name: 'La conto',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, kartoffel, friske tomater',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 15,
      restaurantId: 4,
      name: 'Solo',
      category: 'Pizza',
      description: 'Tomat, ost, hakket oksekød, paprika, løg',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 16,
      restaurantId: 4,
      name: 'La conto',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, kartoffel, friske tomater',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 17,
      restaurantId: 4,
      name: 'Nabo',
      category: 'Pizza',
      description: 'Tomat, ost, hakket oksekød, bacon, spinat, gorgonzola',
      price: 84.00,
    ),
    MenuItemDetail(
      id: 18,
      restaurantId: 4,
      name: 'Sea Food',
      category: 'Pizza',
      description: 'Tomat, ost, tun, rejer, løg',
      price: 82.00,
    ),
    MenuItemDetail(
      id: 19,
      restaurantId: 4,
      name: 'Oral',
      category: 'Pizza',
      description: 'Tomat, ost, kødboller, løg, jalapenos',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 20,
      restaurantId: 4,
      name: 'Kebab Salat Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, salat, dressing',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 21,
      restaurantId: 4,
      name: 'Kyllinge Salat Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, salat, dressing',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 22,
      restaurantId: 4,
      name: 'Vegetariana 1',
      category: 'Vegetar',
      description: 'Tomat, ost, champignon, aspargers, paprika, artiskok',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 23,
      restaurantId: 4,
      name: 'Vegetariana 2',
      category: 'Vegetar',
      description: 'Tomat, ost, kartoffel, oliven, paprika, løg',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 24,
      restaurantId: 4,
      name: 'Kebab Pita',
      category: 'Kebab',
      description: 'Kebab, salat, dressing, friske tomater',
      price: 35.00,
    ),
    MenuItemDetail(
      id: 25,
      restaurantId: 4,
      name: 'Kyllinge Pita',
      category: 'Kebab',
      description: 'Kylling, salat, dressing, friske tomater',
      price: 35.00,
    ),
    MenuItemDetail(
      id: 26,
      restaurantId: 4,
      name: 'Falafel Pita',
      category: 'Kebab',
      description: 'Falafel, salat, dressing, friske tomater',
      price: 35.00,
    ),
    MenuItemDetail(
      id: 27,
      restaurantId: 4,
      name: 'Kebab Durum',
      category: 'Kebab',
      description: 'Kebab, salat, dressing, friske tomater',
      price: 43.00,
    ),
    MenuItemDetail(
      id: 28,
      restaurantId: 4,
      name: 'Kyllinge Durum',
      category: 'Kebab',
      description: 'Kylling, salat, dressing, friske tomater',
      price: 43.00,
    ),
    MenuItemDetail(
      id: 29,
      restaurantId: 4,
      name: 'Falafel Durum',
      category: 'Kebab',
      description: 'Falafel, salat, dressing, friske tomater',
      price: 43.00,
    ),
    MenuItemDetail(
      id: 30,
      restaurantId: 4,
      name: 'Sodavand 0,33 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 15.00,
    ),
    MenuItemDetail(
      id: 31,
      restaurantId: 4,
      name: 'Sodavand 0,5 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 22.00,
    ),
    MenuItemDetail(
      id: 32,
      restaurantId: 4,
      name: 'Sodavand 1,5 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 35.00,
    ),
    MenuItemDetail(
      id: 1,
      restaurantId: 5,
      name: 'Margarita',
      category: 'Pizza',
      description: 'Tomat, ost',
      price: 64.00,
    ),
    MenuItemDetail(
      id: 2,
      restaurantId: 5,
      name: 'Roma',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, ananas',
      price: 70.00,
    ),
    MenuItemDetail(
      id: 3,
      restaurantId: 5,
      name: 'Husets Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, hakket oksekød, paprika, hvidløg',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 4,
      restaurantId: 5,
      name: 'Vesuvio',
      category: 'Pizza',
      description: 'Tomat, ost, skinke',
      price: 70.00,
    ),
    MenuItemDetail(
      id: 5,
      restaurantId: 5,
      name: 'Lyngby',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, champignon, rejer',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 6,
      restaurantId: 5,
      name: 'Lundtofteparken',
      category: 'Pizza',
      description: 'Tomat, ost, cocktailpølser, champignon',
      price: 70.00,
    ),
    MenuItemDetail(
      id: 7,
      restaurantId: 5,
      name: 'La Mafia',
      category: 'Pizza',
      description: 'Tomat, ost, tun, rejer, muslinger',
      price: 74.00,
    ),
    MenuItemDetail(
      id: 8,
      restaurantId: 5,
      name: 'Capricciosa',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, champignon',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 9,
      restaurantId: 5,
      name: 'Princess',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, pepperoni',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 10,
      restaurantId: 5,
      name: 'Cemil',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, champignon, paprika',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 11,
      restaurantId: 5,
      name: 'Hawaii',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, ananas',
      price: 70.00,
    ),
    MenuItemDetail(
      id: 12,
      restaurantId: 5,
      name: 'Italiano',
      category: 'Pizza',
      description: 'Tomat, ost, kødsovs, løg',
      price: 74.00,
    ),
    MenuItemDetail(
      id: 13,
      restaurantId: 5,
      name: 'Walat',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni',
      price: 70.00,
    ),
    MenuItemDetail(
      id: 14,
      restaurantId: 5,
      name: 'Palermo',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, bacon, æg, løg',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 15,
      restaurantId: 5,
      name: 'Milano',
      category: 'Pizza',
      description: 'Tomat, ost, skinke, cocktailpølser',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 16,
      restaurantId: 5,
      name: 'Napoli',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, gorgonzola',
      price: 74.00,
    ),
    MenuItemDetail(
      id: 17,
      restaurantId: 5,
      name: 'Torino',
      category: 'Pizza',
      description: 'Tomat, ost, gorgonzola, kebab, champignon',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 18,
      restaurantId: 5,
      name: 'Rene',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, kartoffel, pesto',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 19,
      restaurantId: 5,
      name: 'Dunar',
      category: 'Pizza',
      description: 'Tomat, ost, kebab',
      price: 70.00,
    ),
    MenuItemDetail(
      id: 20,
      restaurantId: 5,
      name: 'Sorento',
      category: 'Pizza',
      description: 'Tomat, ost, pepperoni, champignon',
      price: 74.00,
    ),
    MenuItemDetail(
      id: 21,
      restaurantId: 5,
      name: 'DTU',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, champignon',
      price: 74.00,
    ),
    MenuItemDetail(
      id: 22,
      restaurantId: 5,
      name: 'Saras Pizza',
      category: 'Pizza',
      description: 'Tomat, ost, kebab, salat, agurk, dressing',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 23,
      restaurantId: 5,
      name: 'Onur',
      category: 'Pizza',
      description: 'Tomat, ost, kylling, salat, agurk, dressing',
      price: 80.00,
    ),
    MenuItemDetail(
      id: 24,
      restaurantId: 5,
      name: 'Vegetariana',
      category: 'Vegetar',
      description: 'Tomat, ost, champignon, løg, paprika, oliven, ananas',
      price: 77.00,
    ),
    MenuItemDetail(
      id: 25,
      restaurantId: 5,
      name: 'Kebab Pita',
      category: 'Kebab',
      description: 'Kebab, salat, agurk, tomat, dressing',
      price: 40.00,
    ),
    MenuItemDetail(
      id: 26,
      restaurantId: 5,
      name: 'Kyllinge Pita',
      category: 'Kebab',
      description: 'Kylling, salat, agurk, tomat, dressing',
      price: 40.00,
    ),
    MenuItemDetail(
      id: 27,
      restaurantId: 5,
      name: 'Falafel Pita',
      category: 'Kebab',
      description: 'Falafel, salat, agurk, tomat, dressing',
      price: 40.00,
    ),
    MenuItemDetail(
      id: 28,
      restaurantId: 5,
      name: 'Kebab Durum',
      category: 'Kebab',
      description: 'Kebab, salat, agurk, tomat, dressing',
      price: 60.00,
    ),
    MenuItemDetail(
      id: 29,
      restaurantId: 5,
      name: 'Kyllinge Durum',
      category: 'Kebab',
      description: 'Kylling, salat, agurk, tomat, dressing',
      price: 60.00,
    ),
    MenuItemDetail(
      id: 30,
      restaurantId: 5,
      name: 'Falafel Durum',
      category: 'Kebab',
      description: 'Falafel, salat, agurk, tomat, dressing',
      price: 60.00,
    ),
    MenuItemDetail(
      id: 31,
      restaurantId: 5,
      name: 'Sodavand 0,33 L',
      category: 'Drinks',
      description: 'Coca Cola, Faxe Kondi, Fanta',
      price: 25.00,
    ),
    MenuItemDetail(
      id: 31,
      restaurantId: 5,
      name: 'Øl 0,33 L',
      category: 'Drinks',
      description: 'Tuborg',
      price: 20.00,
    ),
  ];
}
